apiVersion: v1
kind: Pod
metadata:
  name: high-priority-pod
spec:
  priorityClassName: high-priority
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: 1000Mi
          cpu: 500m
