apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
      command: ["/bin/sh", "-c"]
      args:
        - while true; do echo $(date) Writing data... >> /usr/share/nginx/html/data.txt;
          sleep 5;
          done
      resources:
        requests:
          memory: 1800Mi
          cpu: 1000m
  volumes:
    - name: data
      emptyDir: {}
