apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod
spec:
  priorityClassName: low-priority
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: 1800Mi
          cpu: 1000m
